name: Pull Request

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  run-tests:
    runs-on: blacksmith-2vcpu-ubuntu-2204

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Configure node
        uses: useblacksmith/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: npm

      - run: npm install

      - run: npm run test
